// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClinicWeb.Areas.Appointment.Models;

[Table("Appt_ECPay")]
public partial class ApptEcpay
{
    [Key]
    [Column("fID")]
    public int FId { get; set; }

    [Column("fClinicList_ID")]
    public int FClinicListId { get; set; }

    [Required]
    [Column("fisNHI")]
    public bool? FisNhi { get; set; }

    [Column("fPayable")]
    public int FPayable { get; set; }

    [StringLength(50)]
    public string MerchantTradeNo { get; set; }

    [Column("MemberID")]
    [StringLength(50)]
    public string MemberId { get; set; }

    public int? RtnCode { get; set; }

    [StringLength(50)]
    public string RtnMsg { get; set; }

    [StringLength(50)]
    public string TradeNo { get; set; }

    public int? TradeAmt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentDate { get; set; }

    [StringLength(50)]
    public string PaymentType { get; set; }

    [StringLength(50)]
    public string PaymentTypeChargeFee { get; set; }

    [StringLength(50)]
    public string TradeDate { get; set; }

    public int? SimulatePaid { get; set; }

    [ForeignKey("FClinicListId")]
    [InverseProperty("ApptEcpay")]
    public virtual ApptClinicList FClinicList { get; set; }
}