// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClinicWeb.Areas.Drugs.Models;

[Table("Pharmacy_HealthInformation")]
public partial class PharmacyHealthInformation
{
    [Key]
    public int Id { get; set; }

    [Column("fId_Drug")]
    public int FIdDrug { get; set; }

    [Required]
    [Column("fFileName")]
    [StringLength(100)]
    public string FFileName { get; set; }

    [Column("fFileData")]
    public byte[] FFileData { get; set; }

    [Column("fFilePath")]
    [StringLength(200)]
    public string FFilePath { get; set; }
}