// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClinicWeb.Areas.Room.Models;

public partial class RoomList
{
    [Key]
    [Column("Room_ID")]
    public int RoomId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [Column("Type_ID")]
    public int? TypeId { get; set; }

    [InverseProperty("Room")]
    public virtual ICollection<AppointmentRoomSchedule> AppointmentRoomSchedule { get; set; } = new List<AppointmentRoomSchedule>();

    [ForeignKey("TypeId")]
    [InverseProperty("RoomList")]
    public virtual RoomTypeList Type { get; set; }
}