// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class AppointmentRoomSchedule
{
    public int AppointmentId { get; set; }

    public int? RoomId { get; set; }

    public int? MemberId { get; set; }

    public string StartDate { get; set; }

    public string EndDate { get; set; }

    public int? DoctorId { get; set; }

    public int? NurseId { get; set; }

    public virtual MemberEmployeeList Doctor { get; set; }

    public virtual MemberMemberList Member { get; set; }

    public virtual MemberEmployeeList Nurse { get; set; }

    public virtual RoomList Room { get; set; }
}