// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class ApptPatientStateRef
{
    public int PatientStateId { get; set; }

    public string PatientStateName { get; set; }

    public virtual ICollection<ApptClinicList> ApptClinicList { get; set; } = new List<ApptClinicList>();
}