// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class ApptClinicList
{
    public int ClinicListId { get; set; }

    public int ClinicId { get; set; }

    public int ClinicNumber { get; set; }

    public int MemberId { get; set; }

    public int PatientStateId { get; set; }

    public bool IsCancelled { get; set; }

    public bool IsVip { get; set; }

    public virtual ScheduleClinicInfo Clinic { get; set; }

    public virtual MemberMemberList Member { get; set; }

    public virtual ApptPatientStateRef PatientState { get; set; }
}