// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class AttendanceTExpenseRequests
{
    public int FRequestId { get; set; }

    public int FEmployeeId { get; set; }

    public int FExpenseTypeId { get; set; }

    public decimal? FAmount { get; set; }

    public DateTime? FRequestDate { get; set; }

    public DateTime? FExpenseDate { get; set; }

    public string FRequestsDescription { get; set; }

    public string FApprovalStatus { get; set; }

    public string FPayStatus { get; set; }

    public virtual MemberEmployeeList FEmployee { get; set; }

    public virtual AttendanceTExpenseTypes FExpenseType { get; set; }
}