// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class AttendanceTLeave
{
    public int FLeaveId { get; set; }

    public int FEmployeeId { get; set; }

    public int FLeaveTypeId { get; set; }

    public DateTime? FStartDate { get; set; }

    public DateTime? FEndDate { get; set; }

    public string FSubstitute { get; set; }

    public string FLeaveStatus { get; set; }

    public string FLeaveDescription { get; set; }

    public virtual MemberEmployeeList FEmployee { get; set; }

    public virtual AttendanceTLeaveTypes FLeaveType { get; set; }
}