// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class AttendanceTLeaveTypes
{
    public int FLeaveTypeId { get; set; }

    public string FLeaveTypeName { get; set; }

    public virtual ICollection<AttendanceTLeave> AttendanceTLeave { get; set; } = new List<AttendanceTLeave>();
}