// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class AttendanceTAttendance
{
    public int FAttendanceId { get; set; }

    public int FEmployeeId { get; set; }

    public DateTime? FCheckInTime { get; set; }

    public DateTime? FCheckOutTime { get; set; }

    public string FAttendanceCis { get; set; }

    public DateTime? FWorkDate { get; set; }

    public string FAttendanceCos { get; set; }

    public virtual MemberEmployeeList FEmployee { get; set; }
}