// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class CasesTestReport
{
    public int CaseId { get; set; }

    public int ReportId { get; set; }

    public DateTime TestDate { get; set; }

    public DateTime? ReportDate { get; set; }

    public string TestName { get; set; }

    public string Result { get; set; }

    public string Attachment { get; set; }

    public string ImagePath { get; set; }

    public virtual CasesMainCase Case { get; set; }
}