// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class CasesMainCase
{
    public int CaseId { get; set; }

    public int MemberId { get; set; }

    public string PastHistory { get; set; }

    public string AllergyRecord { get; set; }

    public string FirstvisitDate { get; set; }

    public double? Height { get; set; }

    public double? Weight { get; set; }

    public string Attachment { get; set; }

    public virtual ICollection<CasesMedicalRecords> CasesMedicalRecords { get; set; } = new List<CasesMedicalRecords>();

    public virtual ICollection<CasesPrescription> CasesPrescription { get; set; } = new List<CasesPrescription>();

    public virtual ICollection<CasesTestReport> CasesTestReport { get; set; } = new List<CasesTestReport>();

    public virtual MemberMemberList Member { get; set; }
}