// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class CasesPrescription
{
    public int CaseId { get; set; }

    public int PrescriptionId { get; set; }

    public DateTime PrescriptionDate { get; set; }

    public string Dispensing { get; set; }

    public virtual CasesMainCase Case { get; set; }

    public virtual ICollection<CasesPrescriptionlist> CasesPrescriptionlist { get; set; } = new List<CasesPrescriptionlist>();
}