// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class CasesMedicalRecords
{
    public int CaseId { get; set; }

    public int MrId { get; set; }

    public int ClinicId { get; set; }

    public string Bp { get; set; }

    public int? Pulse { get; set; }

    public double? Bt { get; set; }

    public string Cc { get; set; }

    public string Disposal { get; set; }

    public string Prescribe { get; set; }

    public virtual CasesMainCase Case { get; set; }

    public virtual ScheduleClinicInfo Clinic { get; set; }
}