// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClinicWeb.Models;

[Table("Member_MemberList")]
public partial class MemberMemberList
{
    [Key]
    [Column("Member_ID")]
    public int MemberId { get; set; }

    [Column("Member_Number")]
    public int MemberNumber { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public bool Gender { get; set; }

    [Required]
    [Column("Blood_Type")]
    [StringLength(50)]
    public string BloodType { get; set; }

    [Required]
    [Column("National_ID")]
    [StringLength(50)]
    public string NationalId { get; set; }

    [Required]
    [StringLength(50)]
    public string Address { get; set; }

    [Required]
    [Column("Contact_Address")]
    [StringLength(50)]
    public string ContactAddress { get; set; }

    [Required]
    [StringLength(50)]
    public string Phone { get; set; }

    [Column("Birth_Date", TypeName = "datetime")]
    public DateTime BirthDate { get; set; }

    [Column("ICE_Name")]
    [StringLength(50)]
    public string IceName { get; set; }

    [Column("ICE_Number")]
    [StringLength(50)]
    public string IceNumber { get; set; }

    [Column("Mem_Password")]
    [StringLength(50)]
    public string MemPassword { get; set; }

    [Column("Mem_Email")]
    [StringLength(50)]
    public string MemEmail { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<AppointmentRoomSchedule> AppointmentRoomSchedule { get; set; } = new List<AppointmentRoomSchedule>();

    [InverseProperty("Member")]
    public virtual ICollection<ApptClinicList> ApptClinicList { get; set; } = new List<ApptClinicList>();

    [InverseProperty("Member")]
    public virtual ICollection<CasesMainCase> CasesMainCase { get; set; } = new List<CasesMainCase>();

    [InverseProperty("Member")]
    public virtual ICollection<CasesNewBornList> CasesNewBornList { get; set; } = new List<CasesNewBornList>();

    [InverseProperty("FMember")]
    public virtual ICollection<TCart> TCart { get; set; } = new List<TCart>();

    [InverseProperty("FMember")]
    public virtual ICollection<TCouponWallet> TCouponWallet { get; set; } = new List<TCouponWallet>();

    [InverseProperty("FMember")]
    public virtual ICollection<TOrder> TOrder { get; set; } = new List<TOrder>();
}