// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class MemberCare
{
    public int NewBornId { get; set; }

    public int CareId { get; set; }

    public DateTime CareDate { get; set; }

    public string RecordType { get; set; }

    public string RecordDcp { get; set; }

    public virtual CasesNewBornList NewBorn { get; set; }
}