// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class MemberMemberList
{
    public int MemberId { get; set; }

    public int MemberNumber { get; set; }

    public string Name { get; set; }

    public bool Gender { get; set; }

    public string BloodType { get; set; }

    public string NationalId { get; set; }

    public string Address { get; set; }

    public string ContactAddress { get; set; }

    public string Phone { get; set; }

    public DateTime BirthDate { get; set; }

    public string IceName { get; set; }

    public string IceNumber { get; set; }

    public string MemPassword { get; set; }

    public string MemEmail { get; set; }

    public virtual ICollection<AppointmentRoomSchedule> AppointmentRoomSchedule { get; set; } = new List<AppointmentRoomSchedule>();

    public virtual ICollection<ApptClinicList> ApptClinicList { get; set; } = new List<ApptClinicList>();

    public virtual ICollection<CasesMainCase> CasesMainCase { get; set; } = new List<CasesMainCase>();

    public virtual ICollection<CasesNewBornList> CasesNewBornList { get; set; } = new List<CasesNewBornList>();

    public virtual ICollection<TCart> TCart { get; set; } = new List<TCart>();

    public virtual ICollection<TCouponWallet> TCouponWallet { get; set; } = new List<TCouponWallet>();

    public virtual ICollection<TOrder> TOrder { get; set; } = new List<TOrder>();
}