// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class PharmacyTMedicinesList
{
    public int FIdDrug { get; set; }

    public string FDrugCode { get; set; }

    public string FGenericName { get; set; }

    public string FTradeName { get; set; }

    public string FDrugName { get; set; }

    public string FDrugDose { get; set; }

    public string FMaxDose { get; set; }

    public string FPrecautions { get; set; }

    public string FWarnings { get; set; }

    public string FPregnancyCategory { get; set; }

    public string FApperance { get; set; }

    public string FImages { get; set; }

    public string FStorage { get; set; }

    public string FSupplier { get; set; }

    public string FBrand { get; set; }

    public string FDosage { get; set; }

    public int? FDay { get; set; }

    public int? FEachTime { get; set; }

    public int? FDurationDays { get; set; }

    public int? FQty { get; set; }

    public virtual ICollection<CasesPrescriptionlist> CasesPrescriptionlist { get; set; } = new List<CasesPrescriptionlist>();

    public virtual ICollection<PharmacyTClinicalUseDetails> PharmacyTClinicalUseDetails { get; set; } = new List<PharmacyTClinicalUseDetails>();

    public virtual ICollection<PharmacyTSideEffectDetails> PharmacyTSideEffectDetails { get; set; } = new List<PharmacyTSideEffectDetails>();

    public virtual ICollection<PharmacyTTypeDetails> PharmacyTTypeDetails { get; set; } = new List<PharmacyTTypeDetails>();
}