// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class PharmacyTClinicalUseDetails
{
    public int Id { get; set; }

    public int FIdDrug { get; set; }

    public int FIdClicicalUse { get; set; }

    public virtual PharmacyTClinicalUseList FIdClicicalUseNavigation { get; set; }

    public virtual PharmacyTMedicinesList FIdDrugNavigation { get; set; }
}