// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class PharmacyTClinicalUseList
{
    public int FIdClinicalUse { get; set; }

    public string FClinicalUseCode { get; set; }

    public string FClinicalUse { get; set; }

    public virtual ICollection<PharmacyTClinicalUseDetails> PharmacyTClinicalUseDetails { get; set; } = new List<PharmacyTClinicalUseDetails>();
}