// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class PharmacyTSideEffectList
{
    public int FIdSideEffect { get; set; }

    public string FSideEffectCode { get; set; }

    public string FSideEffect { get; set; }

    public virtual ICollection<PharmacyTSideEffectDetails> PharmacyTSideEffectDetails { get; set; } = new List<PharmacyTSideEffectDetails>();
}