// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class PharmacyTTypeDetails
{
    public int Id { get; set; }

    public int FIdDrug { get; set; }

    public int FIdTpye { get; set; }

    public virtual PharmacyTMedicinesList FIdDrugNavigation { get; set; }

    public virtual PharmacyTTypeList FIdTpyeNavigation { get; set; }
}