// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class RoomTypeList
{
    public int TypeId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<RoomList> RoomList { get; set; } = new List<RoomList>();
}