// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClinicWeb.Models;

public partial class RoomTypeList
{
    [Key]
    [Column("Type_ID")]
    public int TypeId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("Type")]
    public virtual ICollection<RoomList> RoomList { get; set; } = new List<RoomList>();
}