// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class ScheduleClinicInfo
{
    public int ClinicInfoId { get; set; }

    public int DoctorId { get; set; }

    public int ClincRoomId { get; set; }

    public string Date { get; set; }

    public int ClinicTimeId { get; set; }

    public int? LeaveStatus { get; set; }

    public int? RegistrationLimit { get; set; }

    public int? JumpStatus { get; set; }

    public virtual ICollection<ApptClinicList> ApptClinicList { get; set; } = new List<ApptClinicList>();

    public virtual ICollection<CasesMedicalRecords> CasesMedicalRecords { get; set; } = new List<CasesMedicalRecords>();

    public virtual RoomList ClincRoom { get; set; }

    public virtual ScheduleClinicTime ClinicTime { get; set; }

    public virtual MemberEmployeeList Doctor { get; set; }

    public virtual ICollection<ScheduleNurseSchedule> ScheduleNurseSchedule { get; set; } = new List<ScheduleNurseSchedule>();
}