// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class SchedulePharmacistSchedule
{
    public int PharmacistSchedule { get; set; }

    public int EmpId { get; set; }

    public int ShiftsTimeId { get; set; }

    public int LeaveStatus { get; set; }

    public virtual MemberEmployeeList Emp { get; set; }

    public virtual ScheduleStaffPharmacistShiftsTime ShiftsTime { get; set; }
}