// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class ScheduleWardNurseSchedule
{
    public int WardNurseScheduleId { get; set; }

    public int EmpId { get; set; }

    public int WardRoomId { get; set; }

    public int WardShiftsTimeId { get; set; }

    public string Date { get; set; }

    public int LeaveStatus { get; set; }

    public virtual MemberEmployeeList Emp { get; set; }

    public virtual RoomList WardRoom { get; set; }

    public virtual ScheduleWardShiftsTime WardShiftsTime { get; set; }
}