// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class TCouponWallet
{
    public int Id { get; set; }

    public bool FUsed { get; set; }

    public int FCouponId { get; set; }

    public int FMemberId { get; set; }

    public virtual TCoupon FCoupon { get; set; }

    public virtual MemberMemberList FMember { get; set; }
}