// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class TCoupon
{
    public int Id { get; set; }

    public string FName { get; set; }

    public string FCategory { get; set; }

    public byte[] FPicture { get; set; }

    public int FValue { get; set; }

    public int FCriteria { get; set; }

    public string FDescription { get; set; }

    public DateTime FStartDate { get; set; }

    public DateTime FEndDate { get; set; }

    public virtual ICollection<TCouponWallet> TCouponWallet { get; set; } = new List<TCouponWallet>();

    public virtual ICollection<TOrder> TOrderFCouponIdforAmountNavigation { get; set; } = new List<TOrder>();

    public virtual ICollection<TOrder> TOrderFCouponIdforPercentNavigation { get; set; } = new List<TOrder>();

    public virtual ICollection<TOrder> TOrderFCouponIdforShipNavigation { get; set; } = new List<TOrder>();
}