// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class TOrderDetail
{
    public int Id { get; set; }

    public int FAmount { get; set; }

    public int FOrderId { get; set; }

    public int FProductId { get; set; }

    public virtual TOrder FOrder { get; set; }

    public virtual TProduct FProduct { get; set; }
}