// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClinicWeb.Models;

public partial class TProduct
{
    public int Id { get; set; }

    public string FName { get; set; }

    public string FCategory { get; set; }

    public byte[] FPicture { get; set; }

    public int FPrice { get; set; }

    public string FDescription { get; set; }

    public DateTime FStartDate { get; set; }

    public DateTime FEndDate { get; set; }

    public virtual ICollection<TCart> TCart { get; set; } = new List<TCart>();

    public virtual ICollection<TOrderDetail> TOrderDetail { get; set; } = new List<TOrderDetail>();
}